package org.maternalcare.modules.main.user.model.dto

data class UserConditionDto(
    var id: String? = null,
    var userId: String = "",
    var tuberculosisPersonal: Boolean = false,
    var tuberculosisFamily: Boolean = false,
    var heartDiseasesPersonal: Boolean = false,
    var heartDiseasesFamily: Boolean = false,
    var diabetesPersonal: Boolean = false,
    var diabetesFamily: Boolean = false,
    var hypertensionPersonal: Boolean = false,
    var hypertensionFamily: Boolean = false,
    var branchialAsthmaPersonal: Boolean = false,
    var branchialAsthmaFamily: Boolean = false,
    var urinaryTractInfectionPersonal: Boolean = false,
    var urinaryTractInfectionFamily: Boolean = false,
    var parasitismPersonal: Boolean = false,
    var parasitismFamily: Boolean = false,
    var goitersPersonal: Boolean = false,
    var goitersFamily: Boolean = false,
    var anemiaPersonal: Boolean = false,
    var anemiaFamily: Boolean = false,
    var isNormal: Boolean = false,
    var isCritical: Boolean = false,
    var genitalTractInfection: String = "",
    var otherInfectionsDiseases: String = "",
    var notes: String = "",
    var createdById: String? = null,
    var createdAt: String? = null,
    var lastUpdatedById: String? = null,
    var lastUpdatedAt: String? = null,
    var deletedById: String? = null,
    var deletedAt: String? = null,
)
